version: "3.8"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    ports:
      - ${MYSQL_LOCAL_PORT}:${MYSQL_DOCKER_PORT}
    environment:
      - MYSQL_DATABASE=${MYSQLDB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p$MYSQL_PASSWORD"]
      interval: 30s
      timeout: 30s
      retries: 10
  app:
    container_name: app
    image: task_management
    restart: always
    build: .
    ports:
      - ${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}
      - ${DEBUG_PORT}:${DEBUG_PORT}
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PORT: ${MYSQL_DOCKER_PORT}
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:$DEBUG_PORT"
    depends_on:
      mysqldb:
        condition: service_healthy
